version: '3.8'

networks:
  bcmm:

services:
  nginx:
    build:
      context: .
      dockerfile: ./.docker/nginx.dockerfile
    volumes:
      - ./server:/var/www
      - ./.docker/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:80"
      - "443:443"
    container_name: nginx
    networks:
      - bcmm
    depends_on:
      - php
    
  php:
    build:
      context: .
      dockerfile: ./.docker/php.dockerfile
    volumes: 
      - ./server:/var/www
    container_name: php
    networks:
      - bcmm
    depends_on:
      - mysql
      - smtp

  mysql:
    image: mysql
    tty: true
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    command: [mysqld, --default-authentication-plugin=mysql_native_password]
    environment:
      MYSQL_DATABASE: bcmm
      MYSQL_USER: bcmm
      MYSQL_PASSWORD: bcmm
      MYSQL_ROOT_PASSWORD: root
    container_name: mysql
    networks:
      - bcmm

  smtp:
    image: rnwood/smtp4dev:linux-amd64-v3
    ports:
      - 1000:80
    container_name: smtp
    networks:
      - bcmm